// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wetalk/config"
	"wetalk/router"
)

// Injectors from wire.go:

// BuildDependencies 由 wire 自动构建依赖图
func BuildDependencies(cfgPath string) (*router.Dependencies, error) {
	configConfig, err := config.Load(cfgPath)
	if err != nil {
		return nil, err
	}
	hub := NewHub()
	client := NewOSSClient(configConfig)
	dependencies := &router.Dependencies{
		Config:    configConfig,
		Hub:       hub,
		OSSClient: client,
	}
	return dependencies, nil
}
